# docker-compose.yml (수정된 부분)
version: '3.8'

services:
  web:
    # image: php:8.0-apache # 이 줄은 주석 처리하거나 제거합니다.
    build: . # 현재 디렉토리의 Dockerfile을 사용하여 이미지를 빌드합니다.
    container_name: blog_web_server
    volumes:
      - ./www:/var/www/html
    ports:
      - "8080:80"
    networks:
      - blog-net
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    container_name: blog_db_server
    environment:
      MYSQL_ROOT_PASSWORD: your_strong_password! # <<-- **반드시 강력한 비밀번호로 변경하세요!**
      MYSQL_DATABASE: blog_data
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - blog-net
    restart: always

networks:
  blog-net:
    driver: bridge

volumes:
  db_data:
