version: '3.8'

services:
  web:
    # Nginx 대신 PHP가 포함된 Apache 이미지 사용
    image: php:8.0-apache
    container_name: blog_web_server
    # 현재 디렉토리의 www 폴더를 웹 서버 루트(/var/www/html)에 마운트
    volumes:
      - ./www:/var/www/html
    ports:
      # Host:VM 포트는 그대로 8080:80 유지 (VMware 포트 포워딩을 위해)
      - "8080:80"
    networks:
      - blog-net
    # DB 컨테이너가 먼저 실행되도록 보장
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    container_name: blog_db_server
    environment:
      # DB 환경 변수는 그대로 유지
      MYSQL_ROOT_PASSWORD: your_strong_password! 
      MYSQL_DATABASE: blog_data
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - blog-net
    restart: always

networks:
  blog-net:
    driver: bridge

volumes:
  db_data:

